import React, { useEffect, useMemo, useState } from "react";
import { Download, FileText, Upload, Activity } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid } from "recharts";
import { colors, fontDisplay, fontBody } from "../lib/theme";
import { apiGet, apiPost, getSession } from "../lib/teamData";

export default function ReportsPage() {
  const session = getSession();
  const [reports, setReports] = useState([]);
  const [message, setMessage] = useState("");
  const [kind, setKind] = useState("general");
  const [projectId, setProjectId] = useState("");
  const [files, setFiles] = useState([]);
  const [statusMessage, setStatusMessage] = useState("");
  const [projects, setProjects] = useState([]);
  const [summary, setSummary] = useState({ totalTasks: 0, completed: 0, avgProjectProgress: 0 });

  useEffect(() => {
    const isOperations = !session?.role?.toLowerCase().includes("account");
    const query = new URLSearchParams({ userId: session?.id || "", isOperations: String(isOperations) });
    Promise.all([
      apiGet(`/reports?${query}`),
      apiGet("/om/projects"),
      apiGet(`/reports/summary?${query}`),
    ])
      .then(([reportRows, projectRows, reportSummary]) => {
        setReports(reportRows);
        setProjects(projectRows);
        setSummary(reportSummary);
      })
      .catch((error) => console.error("Could not load reports:", error));
  }, [session?.id, session?.role]);

  const assignedProjects = useMemo(() => (
    session?.role?.toLowerCase().includes("account")
      ? projects.filter((project) => project.am === session.name)
      : projects
  ), [projects, session]);

  const perAm = useMemo(() => {
    const counts = new Map();
    for (const project of projects) {
      const name = project.am || "Unassigned";
      counts.set(name, (counts.get(name) || 0) + 1);
    }
    return [...counts].map(([am, count]) => ({ am, projects: count }));
  }, [projects]);

  const progressTrend = useMemo(() => assignedProjects.map((project) => ({
    week: project.title,
    onTime: project.progress,
  })), [assignedProjects]);

  const handleFileChange = (event) => setFiles(Array.from(event.target.files || []));

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!message.trim()) return setStatusMessage("Please add a message for the report.");
    if (kind === "project" && !projectId) return setStatusMessage("Please select a project for a project report.");

    try {
      const report = await apiPost("/reports", {
        authorId: session?.id,
        type: kind,
        projectId: kind === "project" ? projectId : null,
        message: message.trim(),
        attachments: files.map((file) => file.name),
      });
      setReports((current) => [report, ...current]);
      setMessage("");
      setProjectId("");
      setFiles([]);
      setStatusMessage("Report submitted successfully.");
    } catch (error) {
      setStatusMessage(error.message || "Could not submit the report.");
    }
  };

  return (
    <div className="p-4 sm:p-6 space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 style={{ ...fontDisplay, color: colors.primary }} className="text-2xl sm:text-3xl font-bold">Reports</h1>
          <p style={{ ...fontBody, color: colors.muted }} className="mt-2 max-w-2xl text-sm">
            Submit general or project-specific reports and view autogenerated task progress summaries.
          </p>
        </div>
        <div className="grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl p-4" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
            <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Tasks tracked</div>
            <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.primary }}>{summary.totalTasks}</div>
          </div>
          <div className="rounded-xl p-4" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
            <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Tasks complete</div>
            <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.onTrack }}>{summary.completed}</div>
          </div>
          <div className="rounded-xl p-4" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
            <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Avg progress</div>
            <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.primary }}>{summary.avgProjectProgress}%</div>
          </div>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <div className="rounded-lg p-5" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
          <div className="flex items-center gap-2 text-sm font-semibold" style={{ color: colors.primary, ...fontBody }}>
            <FileText size={18} /> Create a report
          </div>
          <form className="mt-5 space-y-4" onSubmit={handleSubmit}>
            <div>
              <label className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Report type</label>
              <div className="mt-2 flex flex-wrap gap-2">
                {[
                  { value: "general", label: "General" },
                  { value: "project", label: "Project" },
                ].map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => setKind(option.value)}
                    className="text-xs font-semibold px-3 py-2 rounded"
                    style={{
                      border: `1px solid ${colors.primary}`,
                      background: kind === option.value ? colors.primary : "transparent",
                      color: kind === option.value ? colors.neutral : colors.primary,
                    }}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            {kind === "project" && (
              <div>
                <label className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Project</label>
                <select
                  value={projectId}
                  onChange={(event) => setProjectId(event.target.value)}
                  className="mt-2 w-full rounded p-3 text-sm"
                  style={{ border: `1px solid ${colors.border}`, ...fontBody }}
                >
                  <option value="">Select a project</option>
                  {assignedProjects.map((project) => (
                    <option key={project.id} value={project.id}>{project.title}</option>
                  ))}
                </select>
              </div>
            )}

            <div>
              <label className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Message</label>
              <textarea
                value={message}
                onChange={(event) => setMessage(event.target.value)}
                rows={5}
                className="mt-2 w-full rounded p-3 text-sm"
                style={{ border: `1px solid ${colors.border}`, ...fontBody }}
                placeholder="Describe what you want the OM to review, plus any blockers or next steps."
              />
            </div>

            <div>
              <label className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Attachments</label>
              <input type="file" multiple onChange={handleFileChange} className="mt-2 w-full text-sm" />
              {files.length > 0 && (
                <div className="mt-2 text-xs" style={{ ...fontBody, color: colors.muted }}>
                  {files.map((file) => file.name).join(", ")}
                </div>
              )}
            </div>

            {statusMessage && (
              <div className="rounded-xl px-4 py-3" style={{ background: "#F9F5FF", border: `1px solid ${colors.border}`, color: colors.primary, ...fontBody }}>
                {statusMessage}
              </div>
            )}

            <button
              type="submit"
              className="flex items-center justify-center gap-2 rounded px-4 py-3 text-sm font-semibold"
              style={{ background: colors.primary, color: colors.neutral, ...fontBody }}
            >
              <Upload size={14} /> Submit report
            </button>
          </form>
        </div>

        <div className="rounded-lg p-5" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
          <div className="flex items-center gap-2 text-sm font-semibold" style={{ color: colors.primary, ...fontBody }}>
            <Activity size={18} /> Autogenerated summary
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            <div className="rounded-xl p-4" style={{ background: "#F6FAF6", border: `1px solid ${colors.border}` }}>
              <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Tasks tracked</div>
              <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.primary }}>{summary.totalTasks}</div>
            </div>
            <div className="rounded-xl p-4" style={{ background: "#EFF6FF", border: `1px solid ${colors.border}` }}>
              <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Completed</div>
              <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.onTrack }}>{summary.completed}</div>
            </div>
            <div className="rounded-xl p-4" style={{ background: "#FFFFFF", border: `1px solid ${colors.border}` }}>
              <div className="text-xs uppercase font-semibold" style={{ ...fontBody, color: colors.muted }}>Avg progress</div>
              <div className="mt-2 text-2xl font-semibold" style={{ ...fontBody, color: colors.primary }}>{summary.avgProjectProgress}%</div>
            </div>
          </div>

          <div className="mt-6 space-y-4">
            {reports.length === 0 ? (
              <div style={{ ...fontBody, color: colors.muted }} className="text-sm">No reports submitted yet.</div>
            ) : (
              reports.slice(0, 4).map((report) => (
                <div key={report.id} className="rounded-xl p-4" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
                  <div className="flex items-center justify-between gap-3 text-sm" style={{ color: colors.muted, ...fontBody }}>
                    <span>{report.createdAt}</span>
                    <span>{report.author}</span>
                  </div>
                  <div className="mt-2 font-semibold" style={{ ...fontBody, color: colors.primary }}>
                    {report.type === "general" ? "General report" : `Project report: ${report.projectTitle}`}
                  </div>
                  <p className="mt-2 text-sm" style={{ ...fontBody, color: colors.muted }}>{report.message}</p>
                  {report.attachments.length > 0 && (
                    <div className="mt-2 text-xs" style={{ ...fontBody, color: colors.muted }}>
                      Attachments: {report.attachments.join(", ")}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <div className="rounded-lg p-5" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
          <h3 style={{ ...fontDisplay, color: colors.primary }} className="text-lg mb-4">Activity by AM</h3>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={perAm}>
              <XAxis dataKey="am" tick={{ fontSize: 11, fontFamily: "Montserrat" }} stroke={colors.muted} />
              <YAxis tick={{ fontSize: 11, fontFamily: "Montserrat" }} stroke={colors.muted} />
              <Tooltip />
              <Bar dataKey="projects" fill={colors.secondary} radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="rounded-lg p-5" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
          <h3 style={{ ...fontDisplay, color: colors.primary }} className="text-lg mb-4">Project progress</h3>
          <ResponsiveContainer width="100%" height={220}>
            <LineChart data={progressTrend}>
              <CartesianGrid stroke={colors.border} strokeDasharray="3 3" />
              <XAxis dataKey="week" tick={{ fontSize: 11, fontFamily: "Montserrat" }} stroke={colors.muted} />
              <YAxis tick={{ fontSize: 11, fontFamily: "Montserrat" }} stroke={colors.muted} domain={[0, 100]} />
              <Tooltip />
              <Line type="monotone" dataKey="onTime" stroke={colors.onTrack} strokeWidth={2} dot={{ r: 4 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="rounded-lg p-5" style={{ background: colors.neutral, border: `1px solid ${colors.border}` }}>
        <div className="flex items-center gap-2 text-sm font-semibold" style={{ color: colors.primary, ...fontBody }}>
          <Activity size={16} /> Latest report activity
        </div>
        <div className="mt-4 space-y-3">
          {reports.slice(0, 3).map((report) => (
            <div key={report.id} className="rounded-lg p-4" style={{ background: "#FFFFFF", border: `1px solid ${colors.border}` }}>
              <div className="flex items-center justify-between gap-3 text-sm" style={{ color: colors.muted, ...fontBody }}>
                <span>{report.createdAt}</span>
                <span>{report.author}</span>
              </div>
              <p className="mt-2" style={{ ...fontBody, color: colors.primary }}>{report.message}</p>
            </div>
          ))}
          {reports.length === 0 && <div style={{ ...fontBody, color: colors.muted }} className="text-sm">No activity yet.</div>}
        </div>
      </div>
    </div>
  );
}
